ERROR - 2024-02-02 04:11:40 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'aitsun_erp_db', 3306, '', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#7 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Fees_and_payments.php(2076): company('1')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Fees_and_payments->add_concession_fee()
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Fees_and_payments.php(2076): company('1')
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Fees_and_payments->add_concession_fee()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-02-02 04:11:40 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'aitsun_erp_db'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`
WHERE `id` = :id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Fees_and_payments.php(2076): company('1')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Fees_and_payments->add_concession_fee()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-02 04:11:47 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'aitsun_erp_db', 3306, '', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#7 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#8 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(31): now_time('1')
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#7 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(31): now_time('1')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-02-02 04:11:47 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'aitsun_erp_db'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`
WHERE `id` = :id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
 6 APPPATH\Helpers\apanel_helper.php(4964): company('1')
 7 APPPATH\Controllers\Home.php(31): now_time('1')
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-02 04:11:48 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'aitsun_erp_db', 3306, '', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#7 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#8 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(31): now_time('1')
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#7 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(31): now_time('1')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-02-02 04:11:48 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'aitsun_erp_db'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`
WHERE `id` = :id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
 6 APPPATH\Helpers\apanel_helper.php(4964): company('1')
 7 APPPATH\Controllers\Home.php(31): now_time('1')
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-02 04:11:49 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'aitsun_erp_db', 3306, '', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#7 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#8 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(31): now_time('1')
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'aitsun_erp_db' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp2\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('1')
#7 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Home.php(31): now_time('1')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-02-02 04:11:49 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'aitsun_erp_db'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`
WHERE `id` = :id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
 6 APPPATH\Helpers\apanel_helper.php(4964): company('1')
 7 APPPATH\Controllers\Home.php(31): now_time('1')
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-02 04:32:23 --> mysqli_sql_exception: Unknown column 'invoice_id' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(242): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\app\Views\fees\view_challan.php(136): concession_data('28195')
#8 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(213): include('C:\\xampp2\\htdoc...')
#9 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp2\htdocs\aitsun-erp\system\Common.php(1184): CodeIgniter\View\View->render('fees/view_chall...', Array, true)
#11 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Fees_and_payments.php(1264): view('fees/view_chall...')
#12 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Fees_and_payments->view_challan('28195')
#13 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
#14 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-02-02 04:32:23 --> Unknown column 'invoice_id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `invoices`
WHERE `invoice_id` = :invoice_id:
AND `concession_for` != :concession_for:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Helpers\apanel_helper.php(242): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Views\fees\view_challan.php(136): concession_data('28195')
 6 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fees\\view_challan.php')
 7 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('fees/view_challan', [], true)
 9 APPPATH\Controllers\Fees_and_payments.php(1264): view('fees/view_challan')
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Fees_and_payments->view_challan('28195')
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-02 04:39:13 --> mysqli_sql_exception: Unknown column 'delete_receipts_and_payments' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(2451): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\app\Views\fees\add_payment_form.php(501): check_permission('1', 'delete_receipts...')
#8 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(213): include('C:\\xampp2\\htdoc...')
#9 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp2\htdocs\aitsun-erp\system\Common.php(1184): CodeIgniter\View\View->render('fees/add_paymen...', Array, true)
#11 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Fees_and_payments.php(2643): view('fees/add_paymen...', Array)
#12 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Fees_and_payments->get_payment_form('28257')
#13 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
#14 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-02-02 04:39:13 --> Unknown column 'delete_receipts_and_payments' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `permission_pos`
WHERE `company_id` = :company_id:
AND `user` = :user:
AND `delete_receipts_and_payments` = :delete_receipts_and_payments:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Helpers\apanel_helper.php(2451): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Views\fees\add_payment_form.php(501): check_permission('1', 'delete_receipts_and_payments')
 6 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fees\\add_payment_form.php')
 7 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('fees/add_payment_form', [], true)
 9 APPPATH\Controllers\Fees_and_payments.php(2643): view('fees/add_payment_form', [...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Fees_and_payments->get_payment_form('28257')
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-02 04:39:18 --> mysqli_sql_exception: Unknown column 'delete_receipts_and_payments' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(2451): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\app\Views\fees\add_payment_form.php(501): check_permission('1', 'delete_receipts...')
#8 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(213): include('C:\\xampp2\\htdoc...')
#9 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp2\htdocs\aitsun-erp\system\Common.php(1184): CodeIgniter\View\View->render('fees/add_paymen...', Array, true)
#11 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Fees_and_payments.php(2643): view('fees/add_paymen...', Array)
#12 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Fees_and_payments->get_payment_form('28257')
#13 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
#14 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-02-02 04:39:18 --> Unknown column 'delete_receipts_and_payments' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `permission_pos`
WHERE `company_id` = :company_id:
AND `user` = :user:
AND `delete_receipts_and_payments` = :delete_receipts_and_payments:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Helpers\apanel_helper.php(2451): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Views\fees\add_payment_form.php(501): check_permission('1', 'delete_receipts_and_payments')
 6 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fees\\add_payment_form.php')
 7 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('fees/add_payment_form', [], true)
 9 APPPATH\Controllers\Fees_and_payments.php(2643): view('fees/add_payment_form', [...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Fees_and_payments->get_payment_form('28257')
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-02 04:39:28 --> mysqli_sql_exception: Unknown column 'delete_receipts_and_payments' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(2451): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\app\Views\fees\add_payment_form.php(501): check_permission('1', 'delete_receipts...')
#8 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(213): include('C:\\xampp2\\htdoc...')
#9 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp2\htdocs\aitsun-erp\system\Common.php(1184): CodeIgniter\View\View->render('fees/add_paymen...', Array, true)
#11 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Fees_and_payments.php(2643): view('fees/add_paymen...', Array)
#12 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Fees_and_payments->get_payment_form('28257')
#13 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
#14 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-02-02 04:39:28 --> Unknown column 'delete_receipts_and_payments' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `permission_pos`
WHERE `company_id` = :company_id:
AND `user` = :user:
AND `delete_receipts_and_payments` = :delete_receipts_and_payments:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Helpers\apanel_helper.php(2451): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Views\fees\add_payment_form.php(501): check_permission('1', 'delete_receipts_and_payments')
 6 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fees\\add_payment_form.php')
 7 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('fees/add_payment_form', [], true)
 9 APPPATH\Controllers\Fees_and_payments.php(2643): view('fees/add_payment_form', [...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Fees_and_payments->get_payment_form('28257')
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fees_and_payments))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-02 05:35:05 --> syntax error, unexpected token "public"
in APPPATH\Controllers\Fees_and_payments.php on line 2144.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Fees_and_payments.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Fees_and_payments')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Fees_and_payments')
 4 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Fees_and_payments', true)
 5 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-02 06:40:57 --> syntax error, unexpected token ","
in APPPATH\Controllers\Fees_and_payments.php on line 2143.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Fees_and_payments.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Fees_and_payments')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Fees_and_payments')
 4 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Fees_and_payments', true)
 5 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-02 06:41:16 --> syntax error, unexpected token ","
in APPPATH\Controllers\Fees_and_payments.php on line 2142.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Fees_and_payments.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Fees_and_payments')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Fees_and_payments')
 4 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Fees_and_payments', true)
 5 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
