CRITICAL - 2024-01-01 03:56:02 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('59', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 04:45:44 --> Undefined variable $inid
in APPPATH\Controllers\Invoices.php on line 1537.
 1 APPPATH\Controllers\Invoices.php(1537): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $inid', 'APPPATH\\Controllers\\Invoices.php', 1537)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->convert_invoice('59')
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 04:45:47 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('61', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 04:45:57 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('59', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 04:47:45 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('62', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 04:48:12 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('62', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 04:49:30 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('63', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 05:01:16 --> syntax error, unexpected token "public"
in APPPATH\Controllers\Invoices.php on line 1610.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Invoices.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Invoices')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Invoices')
 4 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Invoices', true)
 5 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 05:01:40 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('63', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 05:06:42 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('64', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 05:10:28 --> Undefined variable $PaymentsModel
in APPPATH\Controllers\Invoices.php on line 1539.
 1 APPPATH\Controllers\Invoices.php(1539): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $PaymentsModel', 'APPPATH\\Controllers\\Invoices.php', 1539)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->convert_invoice('65')
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 05:10:30 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('66', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 05:13:43 --> Undefined variable $InstallmentsModel
in APPPATH\Controllers\Invoices.php on line 1581.
 1 APPPATH\Controllers\Invoices.php(1581): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $InstallmentsModel', 'APPPATH\\Controllers\\Invoices.php', 1581)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->convert_invoice('64')
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 05:13:54 --> Class "Dompdf\Dompdf" not found
in APPPATH\Controllers\Invoices.php on line 456.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->get_invoice_pdf('67', 'view')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 05:14:04 --> Undefined variable $InstallmentsModel
in APPPATH\Controllers\Invoices.php on line 1581.
 1 APPPATH\Controllers\Invoices.php(1581): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $InstallmentsModel', 'APPPATH\\Controllers\\Invoices.php', 1581)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->convert_invoice('64')
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 05:14:24 --> Class "App\Controllers\InstallmentsModel" not found
in APPPATH\Controllers\Invoices.php on line 1531.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->convert_invoice('64')
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 06:52:08 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 06:52:08 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 06:53:58 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 06:53:58 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 06:54:05 --> mysqli_sql_exception: Unknown column 'company_id' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4479')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 06:54:05 --> Unknown column 'company_id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `invoice_items`
WHERE `company_id` = :company_id:
AND `product_id` = :product_id:
AND `deleted` = :deleted:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4479')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 06:54:12 --> mysqli_sql_exception: Unknown column 'company_id' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4479')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 06:54:12 --> Unknown column 'company_id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `invoice_items`
WHERE `company_id` = :company_id:
AND `product_id` = :product_id:
AND `deleted` = :deleted:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4479')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 06:54:30 --> mysqli_sql_exception: Unknown column 'company_id' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4479')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 06:54:30 --> Unknown column 'company_id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `invoice_items`
WHERE `company_id` = :company_id:
AND `product_id` = :product_id:
AND `deleted` = :deleted:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4479')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:06:57 --> mysqli_sql_exception: Unknown column 'stock_management' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(2445): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\app\Views\user_master\staffs.php(913): check_permission('9556', 'stock_managemen...')
#8 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(213): include('C:\\xampp2\\htdoc...')
#9 C:\xampp2\htdocs\aitsun-erp\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp2\htdocs\aitsun-erp\system\Common.php(1184): CodeIgniter\View\View->render('user_master/sta...', Array, true)
#11 C:\xampp2\htdocs\aitsun-erp\app\Controllers\User_master.php(63): view('user_master/sta...')
#12 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\User_master->index()
#13 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User_master))
#14 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-01-01 07:06:57 --> Unknown column 'stock_management' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `permission_pos`
WHERE `company_id` = :company_id:
AND `user` = :user:
AND `stock_management` = :stock_management:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Helpers\apanel_helper.php(2445): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Views\user_master\staffs.php(913): check_permission('9556', 'stock_management')
 6 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\user_master\\staffs.php')
 7 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('user_master/staffs', [], true)
 9 APPPATH\Controllers\User_master.php(63): view('user_master/staffs')
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\User_master->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User_master))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:10:56 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:10:56 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:11:07 --> mysqli_sql_exception: Unknown column 'company_id' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4479')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:11:07 --> Unknown column 'company_id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `invoice_items`
WHERE `company_id` = :company_id:
AND `product_id` = :product_id:
AND `deleted` = :deleted:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4479')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:12:03 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:12:03 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:12:16 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:12:17 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:12:19 --> mysqli_sql_exception: Unknown column 'company_id' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4478')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:12:19 --> Unknown column 'company_id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `invoice_items`
WHERE `company_id` = :company_id:
AND `product_id` = :product_id:
AND `deleted` = :deleted:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4478')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:29:52 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:29:52 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:55:26 --> Undefined variable $ProductsModel
in APPPATH\Helpers\accounting_helper.php on line 46.
 1 APPPATH\Helpers\accounting_helper.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $ProductsModel', 'APPPATH\\Helpers\\accounting_helper.php', 46)
 2 APPPATH\Controllers\Settings.php(647): transfer_accounting_heads('31', '32', '34')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Settings->start_new_financial_year()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:55:30 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:55:30 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:56:02 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:56:02 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:56:04 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:56:04 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:56:05 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:56:05 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:56:05 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:56:05 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:56:10 --> mysqli_sql_exception: Unknown column 'company_id' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4485')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:56:10 --> Unknown column 'company_id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `invoice_items`
WHERE `company_id` = :company_id:
AND `product_id` = :product_id:
AND `deleted` = :deleted:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4485')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:56:18 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:56:18 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:56:21 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 07:56:21 --> Neither gd-lib or imagick are installed!
in FCPATH\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22.
 1 APPPATH\Controllers\Generate_barcode.php(73): Picqer\Barcode\BarcodeGeneratorPNG->__construct()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Generate_barcode->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Generate_barcode))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:56:21 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:56:21 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:56:26 --> mysqli_sql_exception: Unknown column 'company_id' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4485')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:56:26 --> Unknown column 'company_id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `invoice_items`
WHERE `company_id` = :company_id:
AND `product_id` = :product_id:
AND `deleted` = :deleted:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4485')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:56:26 --> mysqli_sql_exception: Unknown column 'company_id' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4485')
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:56:26 --> Unknown column 'company_id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `invoice_items`
WHERE `company_id` = :company_id:
AND `product_id` = :product_id:
AND `deleted` = :deleted:', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Products.php(2401): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Products->get_adjust_stock('4485')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Products))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:57:22 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:57:22 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:57:29 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:57:29 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:57:32 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:57:32 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:57:33 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:57:33 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:57:36 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:57:36 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 07:57:41 --> mysqli_sql_exception: Unknown column 'ready_to_update' in 'where clause' in C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp2\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp2\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\aitsun-erp\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\aitsun-erp\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp2\htdocs\aitsun-erp\app\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
#7 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
#8 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
#9 C:\xampp2\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp2\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 07:57:41 --> Unknown column 'ready_to_update' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `products`
WHERE `company_id` = :company_id:
AND `created_by` = :created_by:
AND `user_token` = :user_token:
AND `product_method` != :product_method:
AND   (
`ready_to_update` = :ready_to_update:
OR `edit_effected` = :edit_effected:
 )', [...], false)
 2 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Accounting_library.php(40): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Accounting_library->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Accounting_library))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 08:21:39 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'aitsun_app_db' in C:\xampp\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'aitsun_app_db', 3306, '', 0)
#1 C:\xampp\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('7784')
#8 C:\xampp\htdocs\aitsun-erp\app\Controllers\Home.php(30): now_time('7784')
#9 C:\xampp\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 C:\xampp\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'aitsun_app_db' in C:\xampp\htdocs\aitsun-erp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\aitsun-erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\aitsun-erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\aitsun-erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\aitsun-erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\aitsun-erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\aitsun-erp\app\Helpers\apanel_helper.php(4964): company('7784')
#7 C:\xampp\htdocs\aitsun-erp\app\Controllers\Home.php(30): now_time('7784')
#8 C:\xampp\htdocs\aitsun-erp\system\CodeIgniter.php(934): App\Controllers\Home->index()
#9 C:\xampp\htdocs\aitsun-erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\aitsun-erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\aitsun-erp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-01-01 08:21:39 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'aitsun_app_db'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`
WHERE `id` = :id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Helpers\apanel_helper.php(5001): CodeIgniter\BaseModel->first()
 6 APPPATH\Helpers\apanel_helper.php(4964): company('7784')
 7 APPPATH\Controllers\Home.php(30): now_time('7784')
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 08:44:40 --> Undefined variable $indata_due_amount
in APPPATH\Views\invoices\new_create_invoice.php on line 146.
 1 APPPATH\Views\invoices\new_create_invoice.php(146): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $indata_due_amount', 'APPPATH\\Views\\invoices\\new_create_invoice.php', 146)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\invoices\\new_create_invoice.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('invoices/new_create_invoice', [], true)
 5 APPPATH\Controllers\Invoices.php(856): view('invoices/new_create_invoice', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->convert_to_sale('80')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 08:45:26 --> Undefined variable $indata_due_amount
in APPPATH\Views\invoices\new_create_invoice.php on line 146.
 1 APPPATH\Views\invoices\new_create_invoice.php(146): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $indata_due_amount', 'APPPATH\\Views\\invoices\\new_create_invoice.php', 146)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\invoices\\new_create_invoice.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('invoices/new_create_invoice', [], true)
 5 APPPATH\Controllers\Invoices.php(856): view('invoices/new_create_invoice', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->convert_to_sale('80')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 08:49:06 --> Undefined variable $indata_due_amount
in APPPATH\Views\invoices\new_create_invoice.php on line 146.
 1 APPPATH\Views\invoices\new_create_invoice.php(146): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $indata_due_amount', 'APPPATH\\Views\\invoices\\new_create_invoice.php', 146)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\invoices\\new_create_invoice.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('invoices/new_create_invoice', [], true)
 5 APPPATH\Controllers\Invoices.php(856): view('invoices/new_create_invoice', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->convert_to_sale('80')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-01 08:49:37 --> Undefined variable $indata_due_amount
in APPPATH\Views\invoices\new_create_invoice.php on line 149.
 1 APPPATH\Views\invoices\new_create_invoice.php(149): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $indata_due_amount', 'APPPATH\\Views\\invoices\\new_create_invoice.php', 149)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\invoices\\new_create_invoice.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('invoices/new_create_invoice', [], true)
 5 APPPATH\Controllers\Invoices.php(856): view('invoices/new_create_invoice', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Invoices->convert_to_sale('80')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Invoices))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
